### ISSUE TITLE
toogle bar com alguns erros de estilização

### ISSUE THREAD

**Issue by 97revenge** [BotQuest-VW/BQVW-web#32]
[Voce pode ver sobre o erro aqui . ](https://vercel.live/link/bqvw-web-97revenge-vw-senai.vercel.app?page=%2F%3FvercelThreadId%3DdhNnb&via=in-app-copy-link)

**Comment by tamigld** [comment]
corrigi o bug na **branch develop - [commit 718223d](https://github.com/BotQuest-VW/BQVW-web/commit/718223d7276e3b01f89ac93b2e08f8b1fb1ab94c)**.

precisei adicionar cor do fundo do menu lateral, o blur não funciona nele. acredito que seja porque é um componente, então ele "não vê" conteúdo atrás dele para desfocar (_certo falar dessa forma? haha_).

### ❗ importante! 
depois de logado temos o toggle bar também.
é uma boa continuar com ele assim ou um botão direto para sair da conta? (igual ao desktop)
![image](https://github.com/BotQuest-VW/BQVW-web/assets/127408948/b3498605-ab4c-40a7-b325-a6edeb3b3135)

**Comment by 97revenge** [comment]
issue foi finalizado no commit [718223d7](https://github.com/BotQuest-VW/BQVW-web/commit/718223d7276e3b01f89ac93b2e08f8b1fb1ab94c)
